;;; helixel-move.el --- Move & sel commands  -*- lexical-binding: t; -*-

;; Copyright (C) 2025-2026  jixiuf

;; Author: jixiuf
;; Keywords: convenience
;; URL: https://github.com/jixiuf/helixel-mode

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Movement and selection commands for helixel-mode.
;;
;; Provides `helixel-define-movement' for wrapping built-in commands with
;; action tracking, plus hand-written word/WORD/symbol movement commands,
;; line/rectangle selection, surround-thing-at-point, and the line-wise
;; and rect-wise kill/yank helpers.
;;
;; Also houses `helixel--rect-change' and `helixel--rect-replay' for
;; rectangle-change-with-replay support, and `helixel--replace-region'
;; / `helixel-replace-char' for character replacement.

;;; Code:

(require 'cl-lib)
(require 'rect)
(require 'helixel-state)

(declare-function helixel--recreate-line "helixel-common")
(declare-function helixel--recreate-rect "helixel-common")

(defmacro helixel-define-movement (name builtin type &rest options)
  "Define a movement command NAME wrapping BUILTIN with TYPE.

OPTIONS is a plist supporting:
  :dir DIR             — direction, e.g. :dir forward
  :advice              — inject :before advice instead of creating wrapper
  :clear-highlights BOOL — clear highlights before executing (default t)

Wrapper mode (default): delegates to `helixel-define-command'.
  (helixel-define-movement helixel-forward-char forward-char char :dir forward)

Advice mode:
  (helixel-define-movement nil forward-char char :dir forward :advice)

Without highlights clearing:
  (helixel-define-movement helixel-scroll-up scroll-up-command scroll
                        :clear-highlights nil)"
  (declare (indent 1))
  (let* ((dir (plist-get options :dir))
         (advicep (plist-get options :advice))
         (clear (if (plist-member options :clear-highlights)
                    (plist-get options :clear-highlights)
                  t)))
    (if advicep
        `(advice-add #',builtin :before
                     (lambda (&rest _)
                       ,(format "Helixel %s movement advice." type)
                       (helixel-action-start 'movement ',type)
                       ,(when dir
                          `(helixel--live-cat-set-dir ',dir))
                       ,@(when clear
                           '((helixel--clear-highlights)))))
      `(helixel-define-command ,name
           (:category movement :subcat ,type :dir ,dir
                      :clear-highlights ,clear)
         (call-interactively #',builtin)))))

(defmacro helixel-define-movements (&rest specs)
  "Register multiple movements from SPECS.
Each element of SPECS is a list of args for `helixel-define-movement'.

Example:
  (helixel-define-movements
    (helixel-forward-char forward-char char :dir forward)
    (helixel-next-line next-line line :dir forward))"
  `(progn
     ,@(mapcar (lambda (s) `(helixel-define-movement ,@s)) specs)))

;; ── Simple movement wrappers ──
;; Generated by helixel-define-movement for builtin commands that only need
;; action tracking + highlight clearing + call-interactively.

(helixel-define-movement helixel-backward-char backward-char char :dir backward)
(helixel-define-movement helixel-forward-char forward-char char :dir forward)
(helixel-define-movement helixel-next-line next-line line :dir forward)
(helixel-define-movement helixel-previous-line previous-line line :dir backward)
(helixel-define-movement helixel-go-beginning-line beginning-of-line goto)
(helixel-define-movement helixel-go-end-line end-of-line goto)
(helixel-define-movement helixel-go-first-nonwhitespace
  back-to-indentation goto)
(helixel-define-movement helixel-go-end-buffer end-of-buffer goto)
(helixel-define-movement helixel-scroll-up-command scroll-up-command scroll
                         :clear-highlights nil)
(helixel-define-movement helixel-scroll-down-command scroll-down-command scroll
                         :clear-highlights nil)

;; ── Word / WORD / Symbol movement ──

(defun helixel-surround-thing-at-point (&optional thing)
  "Construct a region around THING at point.

Argument THING must be one of the things identified by the package
thingatpt.  Defaults to \\='word."
  (let ((bounds (bounds-of-thing-at-point (or thing 'word))))
    (when bounds
      (set-mark (car bounds))
      (goto-char (cdr bounds))
      (activate-mark))))

(defmacro helixel--with-movement-surround (&rest body)
  "Create a region around movement defined in BODY.
If a region is already active, no new region is created.

Note: `helixel-define-command' handles `clear-highlights'
and `track-visual-move'
automatically, so this macro only does `push-mark' + activate."
  `(let ((current (point)))
     ,@body
     (unless (use-region-p)
       (push-mark current t 'activate))))

(helixel-define-command helixel-forward-word-start
    (:category movement :subcat word :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-word)))

(helixel-define-command helixel-forward-word-end
    (:category movement :subcat word :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-word)))

(helixel-define-command helixel-backward-word-start
    (:category movement :subcat word :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-word -1)))

(helixel-define-command helixel-backward-word-end
    (:category movement :subcat word :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-word -1)))

(helixel-define-command helixel-forward-WORD-start
    (:category movement :subcat WORD :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-WORD)))

(helixel-define-command helixel-forward-WORD-end
    (:category movement :subcat WORD :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-WORD)))

(helixel-define-command helixel-backward-WORD
    (:category movement :subcat WORD :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-WORD -1)))

(helixel-define-command helixel-backward-WORD-end
    (:category movement :subcat WORD :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-WORD -1)))

(helixel-define-command helixel-forward-symbol-start
    (:category movement :subcat symbol :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-symbol)))

(helixel-define-command helixel-forward-symbol-end
    (:category movement :subcat symbol :dir forward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-symbol)))

(helixel-define-command helixel-backward-symbol-start
    (:category movement :subcat symbol :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-beginning 'helixel-symbol -1)))

(helixel-define-command helixel-backward-symbol-end
    (:category movement :subcat symbol :dir backward)
  (helixel--with-movement-surround
   (helixel--forward-end 'helixel-symbol -1)))

(helixel-define-command helixel-go-beginning-buffer
    (:category movement :subcat goto)
  (if current-prefix-arg
      (goto-line (prefix-numeric-value current-prefix-arg))
    (call-interactively #'beginning-of-buffer)))

(helixel-define-command helixel-goto-line
    (:category movement :subcat goto :params (&optional arg))
  (interactive "P")
  (goto-line (if arg
                 (prefix-numeric-value arg)
               (goto-line-read-args))))

;; ── Line / Rect selection ──

(helixel-define-command helixel-select-line
    (:category movement :subcat lineselect :dir forward
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let ((n (or count 1))
        (extending (and (region-active-p) (eolp)))
        (current-prefix-arg nil))
    (if extending
        (dotimes (_ n)
          (call-interactively #'next-line)
          (end-of-line))
      (beginning-of-line)
      (push-mark-command t t)
      (end-of-line)
      (dotimes (_ (1- n))
        (call-interactively #'next-line)
        (end-of-line)))
    (setq helixel--selection-type 'line)
    (let* ((prev-count (helixel-sel-count helixel--repeat-sel-ctx))
           (new-count (if extending (+ prev-count n) n)))
      (setq helixel--repeat-sel-ctx
            (helixel-sel-create 'line `(:dir forward :count ,new-count)
                                #'helixel--recreate-line
                                (if (> new-count 1)
                                    (format "Lx%d" new-count)
                                  "L"))))))

(helixel-define-command helixel-select-line-up
    (:category movement :subcat lineselect :dir backward
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let ((n (or count 1))
        (extending (and (region-active-p) (bolp)))
        (current-prefix-arg nil))
    (if extending
        (dotimes (_ n)
          (call-interactively #'previous-line)
          (beginning-of-line))
      (end-of-line)
      (push-mark-command t t)
      (beginning-of-line)
      (dotimes (_ (1- n))
        (call-interactively #'previous-line)
        (beginning-of-line)))
    (setq helixel--selection-type 'line)
    (let* ((prev-count (helixel-sel-count helixel--repeat-sel-ctx))
           (new-count (if extending (+ prev-count n) n)))
      (setq helixel--repeat-sel-ctx
            (helixel-sel-create 'line `(:dir backward :count ,new-count)
                                #'helixel--recreate-line
                                (if (> new-count 1)
                                    (format "L^x%d" new-count)
                                  "L^"))))))

(helixel-define-command helixel-select-rectangle
    (:category movement :subcat rectselect
               :params (&optional count) :clear-highlights nil)
  (interactive "p")
  (let ((n (or count 1))
        (extending rectangle-mark-mode)
        (current-prefix-arg nil))
    (if extending
        (dotimes (_ n)
          (if (or (> (point) (mark))
                  (and (= (point) (mark))
                       (eq last-command 'helixel-select-rectangle)))
              (forward-line 1)
            (forward-line -1))
          (rectangle--reset-point-crutches))
      (helixel--switch-state 'visual)
      (push-mark (point) t t)
      (rectangle-mark-mode 1)
      (dotimes (_ (1- n))
        (forward-line 1)
        (rectangle--reset-point-crutches)))
    (setq helixel--selection-type 'rect)
    (let* ((prev-count (helixel-sel-count helixel--repeat-sel-ctx))
           (new-count (if extending (+ prev-count n) n)))
      (setq helixel--repeat-sel-ctx
            (helixel-sel-create 'rect `(:count ,new-count)
                                #'helixel--recreate-rect
                                (if (> new-count 1)
                                    (format "rx%d" new-count)
                                  "r"))))))

;;; Line-wise helpers

(defun helixel--yank-handler-line-wise (text)
  "Insert TEXT as a complete line.
Dispatches on `this-command' to decide insertion position."
  (cond
   ((member this-command '(helixel-yank helixel-replace))
    (end-of-line)
    (newline)
    (insert (string-trim-right text "\n"))
    (beginning-of-line)
    (back-to-indentation))
   ((eq this-command 'helixel-yank-before)
    (beginning-of-line)
    (save-excursion
      (insert text)
      (unless (bolp) (newline)))
    (back-to-indentation))
   (t
    (insert text))))

(defun helixel--linewise-text (text)
  "Return a copy of TEXT propertized with line-wise yank-handler.
Ensures TEXT ends with a newline."
  (let ((s (if (and (> (length text) 0)
                    (/= (aref text (1- (length text))) ?\n))
               (concat text "\n")
             text)))
    (propertize s 'yank-handler '(helixel--yank-handler-line-wise nil t))))

(defun helixel--linewise-kill-p (&optional text)
  "Return non-nil if TEXT (default: top of kill ring) was killed line-wise."
  (when-let* ((s (or text (and kill-ring (current-kill 0 t)))))
    (eq (car-safe (get-text-property 0 'yank-handler s))
        'helixel--yank-handler-line-wise)))

(defun helixel--line-bounds-of-region ()
  "Return (BEG . END) expanded to full line boundaries.
BEG is at bol of `region-beginning', END includes the trailing newline."
  (when (use-region-p)
    (let ((beg (save-excursion (goto-char (region-beginning)) (pos-bol)))
          (end (save-excursion (goto-char (region-end))
                               (if (bolp) (point)
                                 (min (1+ (pos-eol)) (point-max))))))
      (cons beg end))))

;;; Rect-wise helpers

(defun helixel--yank-handler-rect-wise (lines)
  "Insert LINES as a rectangle at point."
  (insert-rectangle lines))

(defun helixel--rect-wise-text (strings)
  "Return a propertized string from STRINGS, a list of rect lines.
Tags the text with a rect-wise yank-handler for proper pasting."
  (let ((text (mapconcat #'identity strings "\n")))
    (propertize text 'yank-handler
                (list 'helixel--yank-handler-rect-wise strings t))))

(defun helixel--rect-wise-kill-p (&optional text)
  "Return non-nil if TEXT was killed as a rectangle."
  (when-let* ((s (or text (and kill-ring (current-kill 0 t)))))
    (eq (car-safe (get-text-property 0 'yank-handler s))
        'helixel--yank-handler-rect-wise)))

(defun helixel--rect-bounds-of-region ()
  "Return the rectangle bounds as a list of cons cells (BEG . END).
One per line of the rectangle."
  (when (and (use-region-p) rectangle-mark-mode)
    (extract-rectangle-bounds (region-beginning) (region-end))))

;;; Rect change with replay

(defun helixel--rect-change ()
  "Kill rectangle content, enter insert mode.
Replay typed text on all rectangle lines."
  (let* ((beg (region-beginning))
         (end (region-end))
         (line-count (count-lines beg end))
         (col (save-excursion (goto-char beg) (current-column)))
         (lines (extract-rectangle beg end)))
    (delete-rectangle beg end)
    (kill-new (helixel--rect-wise-text lines))
    (goto-char beg)
    (setq helixel--rect-replay-marker (point-marker))
    (setq helixel--rect-replay-data `(:col ,col :line-count ,line-count))
    (helixel--enter-insert)))

(defun helixel--rect-replay ()
  "Replay inserted text from rect change on remaining rectangle lines."
  (when (and helixel--rect-replay-data helixel--rect-replay-marker)
    (let* ((col (plist-get helixel--rect-replay-data :col))
           (line-count (plist-get helixel--rect-replay-data :line-count))
           (text (buffer-substring helixel--rect-replay-marker (point))))
      (save-excursion
        (dotimes (_ (1- line-count))
          (forward-line 1)
          (move-to-column col t)
          (insert text)))
      (setq helixel--rect-replay-data nil)
      (when helixel--rect-replay-marker
        (set-marker helixel--rect-replay-marker nil)
        (setq helixel--rect-replay-marker nil)))))

;; ── Region replace / replace-char ──

(defun helixel--replace-region (start end text)
  "Replace region from START to END in-place with TEXT."
  (delete-region start end)
  (insert text)
  (helixel--clear-data))

(defun helixel-replace-char (char)
  "Replace selection with CHAR.
If no region is active, replace character at point."
  (interactive "c")
  (helixel-action-start 'edit 'replace-char)
  (helixel--record-edit 'replace-char :char char)
  (if (use-region-p)
      (helixel--replace-region
       (region-beginning) (region-end)
       (make-string (- (region-end) (region-beginning)) char))
    (helixel--replace-region (point) (1+ (point)) char)))

(provide 'helixel-move)
;;; helixel-move.el ends here
